stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  # - deploy
  - upload
  - release
  - checksum

variables:
#  DARWIN_AMD64_BINARY: "oppyChaind-darwin-amd64-${CI_COMMIT_TAG}"
  LINUX_AMD64_BINARY: "oppyChaind-linux-amd64-${CI_COMMIT_TAG}"

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - make build
    - mkdir bin
    - cp oppyChaind bin/oppyChaind
  artifacts:
    paths:
      - bin/

unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - echo "Running unit tests... This will take about 60 seconds."
    - sleep 1
    - echo "Code coverage is 90%"

#lint_code:
#  image: golangci/golangci-lint
#  stage: test
#  before_script:
#    - go get mvdan.cc/gofumpt
#  script:
#    - golangci-lint run -v

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."

upload-job:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/oppyChaind  "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/oppyChaind"'
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file bin/checksum.txt  "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/checksum.txt"'

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release_job'
  release:
    name: '$CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: '$LINUX_AMD64_BINARY'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/oppyChaind"
        - name: 'checksum.txt'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/${CI_COMMIT_TAG}/checksum.txt"
