stages:          # List of stages for jobs, and their order of execution
  - build
  - release

build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - make build

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release_job'
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
