stages:          # List of stages for jobs, and their order of execution
  - build
  - upload
  - release

variables:
  LINUX_AMD64_BINARY: "testingrelease-linux-amd64-${CI_COMMIT_TAG}"
  PACKAGE_REGISTRY_URL: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/testingrelease/${CI_COMMIT_TAG}/"


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - make build
    - ls
    - mkdir bin
    - ls
    - echo "Mock binary for ${LINUX_AMD64_BINARY}" > bin/${LINUX_AMD64_BINARY}
  artifacts:
    paths:
      - bin/

upload-job:
  stage: upload
  image: curlimages/curl:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - curl --header "JOB-TOKEN: ${CI_JOB_TOKEN}" --upload-file bin/${LINUX_AMD64_BINARY} ${PACKAGE_REGISTRY_URL}

release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release_job'
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
    links:
      - name: '$LINUX_AMD64_BINARY'
        url: '$PACKAGE_REGISTRY_URL$LINUX_AMD64_BINARY'
