stages:          # List of stages for jobs, and their order of execution
  - build
  - upload
  - release

variables:
  PACKAGE_REGISTRY_URL: "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/$CI_COMMIT_TAG/"


build-job:       # This job runs in the build stage, which runs first.
  stage: build
  script:
    - echo $PACKAGE_REGISTRY_URL
    - make build

upload-job:
  stage: upload
  image: curlimages/curl:latest
#  rules:
#    - if: $CI_COMMIT_TAG
  script:
    - echo "testing_file" > file.txt
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/test/${CI_COMMIT_TAG}/file.txt"
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file file.txt "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/test/${CI_COMMIT_TAG}/file.txt"'


release-job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
#  rules:
#    - if: $CI_COMMIT_TAG
  script:
    - echo 'running release_job'
  release:
    name: 'Release $CI_COMMIT_TAG'
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: 'test-${CI_COMMIT_TAG}'
          url: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/test/${CI_COMMIT_TAG}/file.txt"