stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  # - deploy


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  script:
    - go test   -v -coverprofile=coverage.out -timeout 15m ./...
    - go tool cover -func=coverage.out

lint_code:
  image: golangci/golangci-lint
  stage: test
  before_script:
    - go get mvdan.cc/gofumpt
  script:
    - golangci-lint run -v --timeout 3600s -c ./.golangci.yml

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
