cache:
  paths:
    - .cache

before_script:
  - mkdir -p .cache
  - export GOPATH="$CI_PROJECT_DIR/.cache"
  - PATH="$GOPATH/bin:$PATH"
  - go get -v -d ./...


stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  # - deploy


unit-test-job:   # This job runs in the test stage.
  stage: test    # It only starts when the job in the build stage completes successfully.
  coverage: '/total:\s+\(statements\)\s+(\d+.\d+\%)/'
  script:
    - go install gotest.tools/gotestsum@latest
    - gotestsum  --junitfile report.xml --format testname  -- -coverprofile=coverage.out -timeout 15m ./...
    - cat coverage.out | grep -v ".pb.go"|grep -v ".gw.go" > cover.out
    - go tool cover -func=cover.out
  artifacts:
    when: always
    reports:
      junit: report.xml
    expire_in: 1 week


lint_code:
  image: golangci/golangci-lint
  stage: test
  before_script:
    - go get mvdan.cc/gofumpt
  script:
    - golangci-lint run -v --timeout 3600s -c ./.golangci.yml

# deploy-job:      # This job runs in the deploy stage.
#   stage: deploy  # It only runs when *both* jobs in the test stage complete successfully.
#   script:
#     - echo "Deploying application..."
#     - echo "Application successfully deployed."
