// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vault/genesis.proto

package types

import (
	fmt "fmt"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the vault module's genesis state.
type GenesisState struct {
	// params defines all the paramaters of related to deposit.
	Params         Params       `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	OutboundTxList []OutboundTx `protobuf:"bytes,5,rep,name=outboundTxList,proto3" json:"outboundTxList"`
	// this line is used by starport scaffolding # genesis/proto/state
	IssueTokenList []*IssueToken `protobuf:"bytes,2,rep,name=issueTokenList,proto3" json:"issueTokenList,omitempty"`
	CreatePoolList []*CreatePool `protobuf:"bytes,3,rep,name=createPoolList,proto3" json:"createPoolList,omitempty"`
	// this line is used by starport scaffolding # ibc/genesis/proto
	ValidatorinfoList []*Validators   `protobuf:"bytes,6,rep,name=validatorinfoList,proto3" json:"validatorinfoList,omitempty"`
	StandbypowerList  []*StandbyPower `protobuf:"bytes,7,rep,name=standbypowerList,proto3" json:"standbypowerList,omitempty"`
	Exported          bool            `protobuf:"varint,4,opt,name=exported,proto3" json:"exported,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_3c6e91fd07fc0e40, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetOutboundTxList() []OutboundTx {
	if m != nil {
		return m.OutboundTxList
	}
	return nil
}

func (m *GenesisState) GetIssueTokenList() []*IssueToken {
	if m != nil {
		return m.IssueTokenList
	}
	return nil
}

func (m *GenesisState) GetCreatePoolList() []*CreatePool {
	if m != nil {
		return m.CreatePoolList
	}
	return nil
}

func (m *GenesisState) GetValidatorinfoList() []*Validators {
	if m != nil {
		return m.ValidatorinfoList
	}
	return nil
}

func (m *GenesisState) GetStandbypowerList() []*StandbyPower {
	if m != nil {
		return m.StandbypowerList
	}
	return nil
}

func (m *GenesisState) GetExported() bool {
	if m != nil {
		return m.Exported
	}
	return false
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "oppyfinance.oppychain.vault.GenesisState")
}

func init() { proto.RegisterFile("vault/genesis.proto", fileDescriptor_3c6e91fd07fc0e40) }

var fileDescriptor_3c6e91fd07fc0e40 = []byte{
	// 392 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0x41, 0x6b, 0xe2, 0x40,
	0x14, 0xc7, 0x93, 0xd5, 0x75, 0x65, 0x5c, 0x64, 0x37, 0xbb, 0xb0, 0xe2, 0x42, 0x56, 0xb6, 0x87,
	0xda, 0x43, 0x13, 0xb0, 0x9f, 0xa0, 0xf6, 0x50, 0x84, 0x82, 0x12, 0xb5, 0x87, 0x5e, 0x64, 0x92,
	0x8c, 0xe9, 0x60, 0x9c, 0x37, 0x64, 0x26, 0x36, 0x7e, 0x8b, 0x1e, 0xfa, 0xa1, 0x3c, 0x7a, 0xec,
	0xa9, 0x14, 0xfd, 0x22, 0x25, 0x93, 0x18, 0xa8, 0x82, 0x78, 0x7b, 0x99, 0x37, 0xbf, 0xdf, 0x7f,
	0xf2, 0x78, 0xe8, 0xd7, 0x02, 0xc7, 0xa1, 0xb4, 0x03, 0xc2, 0x88, 0xa0, 0xc2, 0xe2, 0x11, 0x48,
	0x30, 0xfe, 0x02, 0xe7, 0xcb, 0x29, 0x65, 0x98, 0x79, 0xc4, 0x4a, 0x6b, 0xef, 0x11, 0x53, 0x66,
	0xa9, 0xab, 0xcd, 0x3f, 0x19, 0x01, 0xb1, 0x74, 0x21, 0x66, 0xfe, 0x44, 0x26, 0x19, 0xb5, 0x6b,
	0x50, 0x21, 0x62, 0x32, 0x91, 0x30, 0x23, 0xec, 0x73, 0xc3, 0x8b, 0x08, 0x96, 0x64, 0xc2, 0x01,
	0xc2, 0xbc, 0x91, 0x87, 0x0b, 0x89, 0x67, 0x94, 0x05, 0xf9, 0xe1, 0xef, 0x00, 0x02, 0x50, 0xa5,
	0x9d, 0x56, 0xd9, 0xe9, 0xff, 0x97, 0x32, 0xfa, 0x7e, 0x9b, 0x3d, 0x72, 0x28, 0xb1, 0x24, 0xc6,
	0x35, 0xaa, 0x70, 0x1c, 0xe1, 0xb9, 0x68, 0xe8, 0x2d, 0xbd, 0x5d, 0xeb, 0x9c, 0x59, 0x47, 0x1e,
	0x6d, 0x0d, 0xd4, 0xd5, 0x6e, 0x79, 0xf5, 0xf6, 0x4f, 0x73, 0x72, 0xd0, 0x18, 0xa3, 0xfa, 0xee,
	0x2f, 0x46, 0xc9, 0x1d, 0x15, 0xb2, 0xf1, 0xb5, 0x55, 0x6a, 0xd7, 0x3a, 0xe7, 0x47, 0x55, 0xfd,
	0x02, 0xc9, 0x75, 0x7b, 0x12, 0xa3, 0x8f, 0xea, 0x6a, 0x06, 0xa3, 0x74, 0x04, 0x4a, 0xfb, 0xe5,
	0x04, 0x6d, 0xaf, 0x40, 0x9c, 0x3d, 0x3c, 0x15, 0x66, 0xb3, 0x1b, 0x00, 0x84, 0x4a, 0x58, 0x3a,
	0x41, 0x78, 0x53, 0x20, 0xce, 0x1e, 0x6e, 0x8c, 0xd1, 0xcf, 0x05, 0x0e, 0xa9, 0x8f, 0x25, 0x44,
	0x94, 0x4d, 0x41, 0x39, 0x2b, 0x27, 0x38, 0xef, 0x77, 0x94, 0x70, 0x0e, 0x0d, 0xc6, 0x18, 0xfd,
	0x10, 0x12, 0x33, 0xdf, 0x5d, 0x72, 0x78, 0x22, 0x91, 0xb2, 0x7e, 0x53, 0xd6, 0x8b, 0xa3, 0xd6,
	0x61, 0x06, 0x0d, 0x52, 0xc8, 0x39, 0x50, 0x18, 0x4d, 0x54, 0x25, 0x09, 0x87, 0x48, 0x12, 0xbf,
	0x51, 0x6e, 0xe9, 0xed, 0xaa, 0x53, 0x7c, 0x77, 0x7b, 0xab, 0x8d, 0xa9, 0xaf, 0x37, 0xa6, 0xfe,
	0xbe, 0x31, 0xf5, 0xe7, 0xad, 0xa9, 0xad, 0xb7, 0xa6, 0xf6, 0xba, 0x35, 0xb5, 0x07, 0x3b, 0xa0,
	0x32, 0xc4, 0xae, 0xe5, 0xc1, 0xdc, 0x4e, 0x03, 0x2f, 0xf3, 0x74, 0xbb, 0x48, 0xb7, 0x13, 0x3b,
	0xdb, 0x3f, 0xb9, 0xe4, 0x44, 0xb8, 0x15, 0xb5, 0x68, 0x57, 0x1f, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x6b, 0x0e, 0xa9, 0x12, 0x03, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.StandbypowerList) > 0 {
		for iNdEx := len(m.StandbypowerList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.StandbypowerList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.ValidatorinfoList) > 0 {
		for iNdEx := len(m.ValidatorinfoList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ValidatorinfoList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.OutboundTxList) > 0 {
		for iNdEx := len(m.OutboundTxList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.OutboundTxList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.Exported {
		i--
		if m.Exported {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.CreatePoolList) > 0 {
		for iNdEx := len(m.CreatePoolList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.CreatePoolList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.IssueTokenList) > 0 {
		for iNdEx := len(m.IssueTokenList) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.IssueTokenList[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenesis(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovGenesis(uint64(l))
	if len(m.IssueTokenList) > 0 {
		for _, e := range m.IssueTokenList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.CreatePoolList) > 0 {
		for _, e := range m.CreatePoolList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if m.Exported {
		n += 2
	}
	if len(m.OutboundTxList) > 0 {
		for _, e := range m.OutboundTxList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.ValidatorinfoList) > 0 {
		for _, e := range m.ValidatorinfoList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.StandbypowerList) > 0 {
		for _, e := range m.StandbypowerList {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field IssueTokenList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.IssueTokenList = append(m.IssueTokenList, &IssueToken{})
			if err := m.IssueTokenList[len(m.IssueTokenList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatePoolList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.CreatePoolList = append(m.CreatePoolList, &CreatePool{})
			if err := m.CreatePoolList[len(m.CreatePoolList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Exported", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Exported = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OutboundTxList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OutboundTxList = append(m.OutboundTxList, OutboundTx{})
			if err := m.OutboundTxList[len(m.OutboundTxList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorinfoList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorinfoList = append(m.ValidatorinfoList, &Validators{})
			if err := m.ValidatorinfoList[len(m.ValidatorinfoList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field StandbypowerList", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.StandbypowerList = append(m.StandbypowerList, &StandbyPower{})
			if err := m.StandbypowerList[len(m.StandbypowerList)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
