// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: vault/issue_token.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IssueToken struct {
	Creator  github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=creator,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"creator,omitempty"`
	Index    string                                        `protobuf:"bytes,2,opt,name=index,proto3" json:"index,omitempty"`
	Coin     *github_com_cosmos_cosmos_sdk_types.Coin      `protobuf:"bytes,3,opt,name=coin,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Coin" json:"coin,omitempty"`
	Receiver github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,4,opt,name=receiver,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"receiver,omitempty"`
	IsIBC    bool                                          `protobuf:"varint,5,opt,name=isIBC,proto3" json:"isIBC,omitempty"`
}

func (m *IssueToken) Reset()         { *m = IssueToken{} }
func (m *IssueToken) String() string { return proto.CompactTextString(m) }
func (*IssueToken) ProtoMessage()    {}
func (*IssueToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_7dedd3064ce27bad, []int{0}
}
func (m *IssueToken) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IssueToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IssueToken.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IssueToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IssueToken.Merge(m, src)
}
func (m *IssueToken) XXX_Size() int {
	return m.Size()
}
func (m *IssueToken) XXX_DiscardUnknown() {
	xxx_messageInfo_IssueToken.DiscardUnknown(m)
}

var xxx_messageInfo_IssueToken proto.InternalMessageInfo

func (m *IssueToken) GetCreator() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Creator
	}
	return nil
}

func (m *IssueToken) GetIndex() string {
	if m != nil {
		return m.Index
	}
	return ""
}

func (m *IssueToken) GetReceiver() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func (m *IssueToken) GetIsIBC() bool {
	if m != nil {
		return m.IsIBC
	}
	return false
}

func init() {
	proto.RegisterType((*IssueToken)(nil), "oppyfinance.oppychain.vault.IssueToken")
}

func init() { proto.RegisterFile("vault/issue_token.proto", fileDescriptor_7dedd3064ce27bad) }

var fileDescriptor_7dedd3064ce27bad = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x91, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x86, 0xeb, 0xd2, 0x42, 0xb1, 0x98, 0xa2, 0x4a, 0x44, 0x20, 0xb9, 0x15, 0x0b, 0x5d, 0x12,
	0x0b, 0xf1, 0x04, 0x4d, 0xa6, 0x08, 0xb1, 0x44, 0x4c, 0x2c, 0x28, 0x75, 0x4c, 0x6a, 0xb5, 0xf5,
	0x45, 0xb6, 0x53, 0xb5, 0x6f, 0xc1, 0xca, 0x1b, 0x75, 0xec, 0x88, 0x18, 0x22, 0x94, 0xbc, 0x05,
	0x13, 0x8a, 0x53, 0x3a, 0x23, 0x26, 0xdf, 0x49, 0x77, 0xdf, 0x7f, 0xfa, 0x8c, 0x2f, 0xd7, 0x49,
	0xb1, 0x34, 0x54, 0x68, 0x5d, 0xf0, 0x17, 0x03, 0x0b, 0x2e, 0xfd, 0x5c, 0x81, 0x01, 0xe7, 0x1a,
	0xf2, 0x7c, 0xfb, 0x2a, 0x64, 0x22, 0x19, 0xf7, 0x9b, 0x9a, 0xcd, 0x13, 0x21, 0x7d, 0x3b, 0x7e,
	0x35, 0xcc, 0x20, 0x03, 0x3b, 0x47, 0x9b, 0xaa, 0x5d, 0xb9, 0x79, 0xef, 0x62, 0x1c, 0x35, 0xa0,
	0xa7, 0x86, 0xe3, 0x3c, 0xe0, 0x33, 0xa6, 0x78, 0x62, 0x40, 0xb9, 0x68, 0x8c, 0x26, 0x17, 0xc1,
	0xdd, 0x77, 0x39, 0xf2, 0x32, 0x61, 0xe6, 0xc5, 0xcc, 0x67, 0xb0, 0xa2, 0x0c, 0xf4, 0x0a, 0xf4,
	0xe1, 0xf1, 0x74, 0xba, 0xa0, 0x66, 0x9b, 0x73, 0xed, 0x4f, 0x19, 0x9b, 0xa6, 0xa9, 0xe2, 0x5a,
	0xc7, 0xbf, 0x04, 0x67, 0x88, 0xfb, 0x42, 0xa6, 0x7c, 0xe3, 0x76, 0xc7, 0x68, 0x72, 0x1e, 0xb7,
	0x8d, 0x13, 0xe2, 0x1e, 0x03, 0x21, 0xdd, 0x13, 0xcb, 0xa7, 0xbb, 0x72, 0x84, 0x3e, 0xcb, 0xd1,
	0xed, 0x1f, 0x32, 0x42, 0x10, 0x32, 0xb6, 0xcb, 0xce, 0x23, 0x1e, 0x28, 0xce, 0xb8, 0x58, 0x73,
	0xe5, 0xf6, 0xfe, 0x7b, 0xe8, 0x11, 0x61, 0x2f, 0xd5, 0x51, 0x10, 0xba, 0xfd, 0x31, 0x9a, 0x0c,
	0xe2, 0xb6, 0x09, 0xa2, 0x5d, 0x45, 0xd0, 0xbe, 0x22, 0xe8, 0xab, 0x22, 0xe8, 0xad, 0x26, 0x9d,
	0x7d, 0x4d, 0x3a, 0x1f, 0x35, 0xe9, 0x3c, 0xd3, 0x4c, 0x98, 0x65, 0xd2, 0x06, 0x35, 0x9e, 0xbd,
	0x83, 0x74, 0x7a, 0x94, 0x4e, 0x37, 0xb4, 0xfd, 0x25, 0x9b, 0x3a, 0x3b, 0xb5, 0xb6, 0xef, 0x7f,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x9f, 0x16, 0x78, 0xcf, 0xbb, 0x01, 0x00, 0x00,
}

func (m *IssueToken) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IssueToken) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IssueToken) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.IsIBC {
		i--
		if m.IsIBC {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.Receiver) > 0 {
		i -= len(m.Receiver)
		copy(dAtA[i:], m.Receiver)
		i = encodeVarintIssueToken(dAtA, i, uint64(len(m.Receiver)))
		i--
		dAtA[i] = 0x22
	}
	if m.Coin != nil {
		{
			size := m.Coin.Size()
			i -= size
			if _, err := m.Coin.MarshalTo(dAtA[i:]); err != nil {
				return 0, err
			}
			i = encodeVarintIssueToken(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Index) > 0 {
		i -= len(m.Index)
		copy(dAtA[i:], m.Index)
		i = encodeVarintIssueToken(dAtA, i, uint64(len(m.Index)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintIssueToken(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintIssueToken(dAtA []byte, offset int, v uint64) int {
	offset -= sovIssueToken(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IssueToken) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovIssueToken(uint64(l))
	}
	l = len(m.Index)
	if l > 0 {
		n += 1 + l + sovIssueToken(uint64(l))
	}
	if m.Coin != nil {
		l = m.Coin.Size()
		n += 1 + l + sovIssueToken(uint64(l))
	}
	l = len(m.Receiver)
	if l > 0 {
		n += 1 + l + sovIssueToken(uint64(l))
	}
	if m.IsIBC {
		n += 2
	}
	return n
}

func sovIssueToken(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozIssueToken(x uint64) (n int) {
	return sovIssueToken(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IssueToken) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowIssueToken
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IssueToken: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IssueToken: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIssueToken
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIssueToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = append(m.Creator[:0], dAtA[iNdEx:postIndex]...)
			if m.Creator == nil {
				m.Creator = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Index", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthIssueToken
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthIssueToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Index = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Coin", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIssueToken
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIssueToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Coin
			m.Coin = &v
			if err := m.Coin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Receiver", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthIssueToken
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthIssueToken
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Receiver = append(m.Receiver[:0], dAtA[iNdEx:postIndex]...)
			if m.Receiver == nil {
				m.Receiver = []byte{}
			}
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsIBC", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsIBC = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipIssueToken(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthIssueToken
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipIssueToken(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowIssueToken
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowIssueToken
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthIssueToken
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupIssueToken
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthIssueToken
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthIssueToken        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowIssueToken          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupIssueToken = fmt.Errorf("proto: unexpected end of group")
)
